language: python
env:
  - "PYTHONPATH=/home/jenkins/warno-vagrant/data_store/data"
  - "DATA_STORE_PATH=/home/jenkins/warno-vagrant/data_store/data/"
  - "USER_PORTAL_PATH=/home/jenkins/warno-vagrant/warno_user_portal/src/"

matrix:
  include:
      - python: "2.7"
        env:
        - PYTHON_VERSION="2.7"
        - NOSE_ARGS="-v --no-skip --exclude-dir=selenium_tests --exclude-dir=warno_user_portal/src/tests"
        - COVERALLS="true"

before_install:
    - pip install pytest pytest-cov nose nose-exclude
    - pip install coveralls

install: source continuous_integration/install.sh

before_script: source utility_setup_scripts/set_env_for_testing.sh

script:
    - nosetests --exclude-dir=selenium_tests --exclude-dir=warno_user_portal/src/tests --with-xunit
