
postgres:
  build: ./postgres
  env_file: .env
  ports:
    - "5432:5432"

eventmanager:
  build: ./warno-event-manager
  command: bash -c "/usr/sbin/sshd && python warno_event_manager.py "
  links:
    - postgres
  volumes:
    - /vagrant/warno-event-manager/src:/opt/warno-event-manager
  env_file: .env

userportal:
  build: ./warno-user-portal
  command: bash -c "/usr/sbin/sshd && python manage.py runserver 0.0.0.0:80"
  links:
    - postgres
    - eventmanager
  volumes:
    - /vagrant/warno-user-portal/src:/opt/warno-user-portal
  env_file: .env

proxy:
  build: ./proxy
  ports:
    - "80:80"
  volumes:
    - /vagrant/proxy/sites-enabled:/etc/nginx/sites-enabled
  links:
    - eventmanager
    - userportal
  env_file: .env

agent:
    build: ./warno-agent
    command: python warno-agent.py
    ports:
      - "6310:6310"
    volumes:
        - /vagrant/warno-agent/src:/opt/agent
    links:
      - eventmanager
      - proxy
    env_file: .env

sshd:
  build: ./sshd
  ports:
    - "10002:22"
  links:
    - eventmanager
    - userportal
    - proxy
    - postgres
  env_file: .env
