
postgres:
  build: ./postgres
  env_file: .env
  ports:
    - "5432:5432"

eventmanager:
  build: ./warno-event-manager
  command: bash -c "/usr/sbin/sshd && python warno_event_manager.py "
  links:
    - postgres
  volumes:
    - /vagrant/warno-event-manager/src:/opt/warno-event-manager
  env_file: .env

djangoapp:
  build: ./django-app
  command: "python manage.py runserver 0.0.0.0:80"
  links:
    - postgres
    - eventmanager
  volumes:
    - /vagrant/django-app/src:/opt/django-app
  env_file: .env

proxy:
  build: ./proxy
  ports:
    - "80:80"
  volumes:
    - /vagrant/proxy/sites-enabled:/etc/nginx/sites-enabled
  links:
    - eventmanager
    - djangoapp
  env_file: .env

sshd:
  build: ./sshd
  ports:
    - "10002:22"
  links:
    - eventmanager
    - djangoapp
    - proxy
    - postgres
  env_file: .env
