
postgres:
  build: ./postgres
  env_file: .env
  ports:
    - "5432:5432"

flaskapp:
  build: ./flask-app
  command: "python hello.py"
  links:
    - postgres
  volumes:
    - /vagrant/flask-app/src:/opt/flask-app
  env_file: .env
  ports:
    - "22:10022"

djangoapp:
  build: ./django-app
  command: "python manage.py runserver 0.0.0.0:80"
  links:
    - postgres
    - flaskapp
  volumes:
    - /vagrant/django-app/src:/opt/django-app
  env_file: .env

proxy:
  build: ./proxy
  ports:
    - "80:80"
  volumes:
    - /vagrant/proxy/sites-enabled:/etc/nginx/sites-enabled
  links:
    - flaskapp
    - djangoapp
  env_file: .env
