"""Added valid_columns and aliases tables

Revision ID: 37b800d049f7
Revises: 717007ed12a3
Create Date: 2016-05-31 16:51:13.332826

"""

# revision identifiers, used by Alembic.
revision = '37b800d049f7'
down_revision = '717007ed12a3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aliases',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.Column('name_short', sa.String(), nullable=False),
    sa.Column('name_long', sa.String()),
    sa.Column('unit', sa.String()),
    sa.Column('role', sa.String()),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('valid_columns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=False),
    sa.Column('table_name', sa.String(), nullable=False),
    sa.Column('column_name', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('valid_columns')
    op.drop_table('aliases')
    ### end Alembic commands ###
