"""Added location data to instruments

Revision ID: 6c29ac6e4c56
Revises: efc4fcb09bd3
Create Date: 2017-04-27 19:41:29.637843

"""

# revision identifiers, used by Alembic.
revision = '6c29ac6e4c56'
down_revision = 'efc4fcb09bd3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instruments', sa.Column('effective_radius', sa.Float(), nullable=False, server_default='0.0'))
    op.add_column('instruments', sa.Column('latitude', sa.Float(), nullable=False, server_default='-999.0'))
    op.add_column('instruments', sa.Column('longitude', sa.Float(), nullable=False, server_default='-999.0'))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'longitude')
    op.drop_column('instruments', 'latitude')
    op.drop_column('instruments', 'effective_radius')
    ### end Alembic commands ###
