"""Dashboard string for user

Revision ID: 8013d1cf2cff
Revises: 06089e44402d
Create Date: 2016-09-30 20:43:47.667162

"""

# revision identifiers, used by Alembic.
revision = '8013d1cf2cff'
down_revision = '06089e44402d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('dashboard', sa.String(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'dashboard')
    ### end Alembic commands ####