"""Default user authorizations to 'user', remove instrument frequency_band column

Revision ID: 952e55f64a88
Revises: d84d78718caa
Create Date: 2017-03-02 17:33:25.424525

"""

# revision identifiers, used by Alembic.
revision = '952e55f64a88'
down_revision = 'd84d78718caa'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instruments', 'frequency_band')
    op.execute("UPDATE users SET authorizations='user' WHERE authorizations IS NULL")
    op.alter_column('users', 'authorizations',
               existing_type=sa.VARCHAR(),
               nullable=False,
               server_default='user')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'authorizations',
               existing_type=sa.VARCHAR(),
               nullable=True,
               server_default=None)
    op.add_column('instruments', sa.Column('frequency_band', sa.VARCHAR(length=2), autoincrement=False, nullable=True))
    ### end Alembic commands ###
