"""Added dashboards table

Revision ID: d84d78718caa
Revises: 06089e44402d
Create Date: 2016-10-06 22:39:45.839321

"""

# revision identifiers, used by Alembic.
revision = 'd84d78718caa'
down_revision = '06089e44402d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dashboards',
    sa.Column('dashboard_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('schematic', sa.String(), nullable=False),
    sa.Column('private', sa.Boolean(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.user_id'], ),
    sa.PrimaryKeyConstraint('dashboard_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dashboards')
    ### end Alembic commands ###
