"""Added instrument links table

Revision ID: efc4fcb09bd3
Revises: 5fe85b823f57
Create Date: 2017-04-12 20:53:31.097535

"""

# revision identifiers, used by Alembic.
revision = 'efc4fcb09bd3'
down_revision = '5fe85b823f57'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instrument_links',
    sa.Column('link_id', sa.Integer(), nullable=False),
    sa.Column('instrument_id', sa.Integer(), nullable=True),
    sa.Column('text', sa.String(), nullable=True),
    sa.Column('link', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['instrument_id'], ['instruments.instrument_id'], ),
    sa.PrimaryKeyConstraint('link_id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('instrument_links')
    ### end Alembic commands ###
